name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      working-directory: snakeGame
      run: chmod +x gradlew

    - name: Build project
      working-directory: snakeGame
      run: ./gradlew build

    - name: Run Unit Tests
      working-directory: snakeGame
      run: ./gradlew testDebugUnitTest

    # - name: Run Instrumented (UI) Tests
    #   working-directory: snakeGame
    #   run: ./gradlew connectedDebugAndroidTest
